# Generated by Django 3.0.5 on 2020-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200513_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('test_center', 'Test Center'), ('supermarket', 'Supermarket')], default='test_center', max_length=50, verbose_name='category type'),
        ),
    ]
