# Generated by Django 3.0.5 on 2020-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200513_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='lga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
